### PR TITLE
Compiler 0.12

### PR DESCRIPTION
**Pull request by AlexMouton**
Hi Phil.
Havn't even run this yet but...

A

### CODE REVIEW

**Review by paf31 — APPROVED** [review]
Thanks!

**Comment by paf31** [comment]
This looks good. I've added you as a collaborator on the repo, so you should have push access. Please feel free to merge and release this once you're happy. I think Travis can be made to work by copying the config from one of my other repos.

**Comment by AlexMouton** [comment]
merged locally

**Comment by AlexMouton** [comment]
hey @paf31 jk. Doesnt look like I can do the merge but it was published from my branch ?? err.

**Comment by paf31** [comment]
Thanks!

**Pull request merged**
