### PR TITLE
v3.0.0

### PR DESCRIPTION
**Pull request by AlexMouton**
can you fast forward this?

### CODE REVIEW

**Comment by paf31** [comment]
Wait I'm confused :) I just released the other branch.

**Comment by AlexMouton** [comment]
this one just has the v3.0.0 on the top

**Comment by AlexMouton** [comment]
lol disaster. sorry.

**Comment by AlexMouton** [comment]
the released 3.0.0 and tag are on my branch. 
If we cherry pick and retag, code is identical.  i mean... its "fixed" ?

**Comment by paf31** [comment]
What do you mean by "on the top"?

I think what's released is good though, no?

**Comment by AlexMouton** [comment]
code is good, its just that the tag and tag commit are on my main.

**Comment by paf31** [comment]
Do you mean what's released to Pursuit? I'm not worried about that tbh.

**Comment by paf31** [comment]
If you made a tag on your fork, that shouldn't affect bower, so I think it's okay.

**Comment by AlexMouton** [comment]
not sure how pursuit would handle publishing to the same tag twice. hopefully idempotent. so tag and publish should square it up but sure.

**Pull request closed without merging**
